compare provided solution names against solution-names.txt before checking them in the dev environment (#10)

diff --git a/.github/actions/validate-solutions-list/action.yml b/.github/actions/validate-solutions-list/action.yml
--- a/.github/actions/validate-solutions-list/action.yml
+++ b/.github/actions/validate-solutions-list/action.yml
@@ -39,6 +39,26 @@ runs:
           echo "using default solutions list: $solutions"
         else
           solutions=`echo $trimmedSolutions | sed 's/\s*,\s*/,/g'`
+
+          solutionsList=$(echo $solutions | tr "," "\n")
+          validSolutionsList=$(echo `sed -z 's/\r\?\n/,/g' solution-names.txt` | tr "," "\n")
+          
+          for solution in $solutionsList
+          do
+            found=0
+            for validSolution in $validSolutionsList
+            do
+              if [[ $solution == $validSolution ]]
+              then
+                found=1
+              fi
+            done
+            if [[ $found -eq 0 ]]
+            then
+              echo "::error title=Invalid Solution Name::$solution does not exist in solution-names.txt"
+              exit 1
+            fi
+          done
         fi
         echo "::set-output name=solutions::$solutions"
 
@@ -66,7 +86,7 @@ runs:
             jq '.value | length')
           if [[ $results -eq 0 ]]
           then
-            echo "::error title=Missing Solution::$solution does not exist"
+            echo "::error title=Missing Solution::$solution does not exist in the development environment"
             exit 1
           fi
         done
